version: '3'
services:
  postgres:
    container_name: masonite-test-postgres
    image: postgres:10.8
    environment:
      POSTGRES_USER: ${POSTGRES_DATABASE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_DATABASE}
    ports:
      # will assign a random free host port
      - 5432/tcp
    # needed because the postgres container does not provide a healthcheck
    healthcheck:
      test: ['pg_isready']
      interval: 10s 
      timeout: 5s
      retries: 5

  mysql:
    container_name: masonite-test-mysql
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: ${MYSQL_DATABASE_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_USER: ${MYSQL_DATABASE_USER}
    ports:
      - 3306
    healthcheck:
      test: ['mysqladmin ping']
      interval: 10s 
      timeout: 5s
      retries: 3