from cleo import Command
from ..migrations import Migration


class MigrateSQLCommand(Command):
    """
    Show the SQL generated by migration.

    migrate:sql
        {--m|migration=None} : The migration to see its sql
        {--c|connection=default : The connection you want to use to show sql from migration}
    """

    def handle(self):

        if not self.option("migration"):
            raise Exception("Migration option is required")

        schema = Migration(
            command_class=self, connection=self.option("connection"), dry=True
        )
        migration = self.option("migration")
        schema
