from .BelongsTo import BelongsTo as belongs_to
from .BelongsToMany import BelongsToMany as belongs_to_many
from .HasOne import HasOne as has_one
from .HasMany import HasMany as has_many
from .HasOneThrough import HasOneThrough as has_one_through
from .HasManyThrough import HasManyThrough as has_many_through
from .MorphTo import MorphTo as morph_to
from .MorphToMany import MorphToMany as morph_to_many
from .MorphOne import MorphOne as morph_one
from .MorphMany import MorphMany as morph_many
